insert into houses (name) values ('Hufflepuff'), ('Gryffindor'), ('Ravenclaw'), ('Slytherin')

insert into teachers (name, house_id) values ('Severus Snape', 4),
  ('Minerva McGonagall', 2),
  ('Filius Flitwick', 3),
  ('Pomona Sprout', 1),
  ('Remus Lupin', null),
  ('Aurora Sinistra', null),
  ('Rolanda Hooch', null),
  ('Charity Burbage', null),
  ('Cuthbert Binns', null);

insert into classes (subject, teacher_id) values
  ('Potions',
    (select id from teachers where name='Severus Snape')),
  ('Transfiguration',
    (select id from teachers where name='Minerva McGonagall')),
  ('Charms',
    (select id from teachers where name='Filius Flitwick')),
  ('Herbology',
    (select id from teachers where name='Pomona Sprout')),
  ('Defense Against the Dark Arts',
    (select id from teachers where name='Remus Lupin')),
  ('Astronomy',
    (select id from teachers where name='Aurora Sinistra')),
  ('Flying',
    (select id from teachers where name='Rolanda Hooch')),
  ('Muggle Studies',
    (select id from teachers where name='Charity Burbage')),
  ('History of Magic',
    (select id from teachers where name='Cuthbert Binns'));

insert into parents (name) values
  ('Brendan Sporer'),
  ('Devon Brown'),
  ('Heaven McKenzie'),
  ('Leopoldo Glover Mrs.'),
  ('Syble Kshlerin'),
  ('Krystal Boyer'),
  ('Shakira Zemlak'),
  ('Jerrold Schiller'),
  ('Juston Ruecker'),
  ('Astrid Dietrich'),
  ('Gerard Volkman'),
  ('Torrance Schiller'),
  ('Dorian Becker'),
  ('Bert Nikolaus'),
  ('Dax Shields'),
  ('Wilhelm Schneider'),
  ('Quincy McDermott'),
  ('Angeline Mayert'),
  ('Elisa Kautzer'),
  ('Christine Pacocha'),
  ('Garrett Morar'),
  ('Oma Tromp'),
  ('Ms. Leo Champlin'),
  ('Melany Schowalter'),
  ('Israel Lubowitz Mr.'),
  ('Shany Harris'),
  ('Ally Mraz'),
  ('Emmy Hoeger'),
  ('Jermain Blick'),
  ('Robert Crooks'),
  ('Rey Douglas'),
  ('Rossie Bode'),
  ('Mrs. Koby Homenick'),
  ('Mrs. Cleta Kessler'),
  ('Maci Goodwin'),
  ('Karli Swaniawski'),
  ('Candida O\'Conner Mrs.'),
  ('Tommie Pollich Mr.'),
  ('Petra Moen'),
  ('Rubie Runolfsson'),
  ('Hallie Feest Mrs.'),
  ('Simone O\'Reilly'),
  ('Marty Will'),
  ('Markus Wilderman'),
  ('Stephany Stamm Miss'),
  ('Miss Derrick Pfannerstill'),
  ('Mrs. Marcus Baumbach'),
  ('Baron Larkin'),
  ('Zoie Bernhard'),
  ('Cathrine Heidenreich'),
  ('Christy Cremin'),
  ('Clark Oberbrunner'),
  ('Brando Howell'),
  ('Neva Dach'),
  ('Magali Waelchi'),
  ('Loren Boyer'),
  ('Amalia Murphy'),
  ('Elizabeth Torphy Ms.'),
  ('Raleigh Buckridge'),
  ('Reggie Considine'),
  ('Nash Kozey'),
  ('Jevon Erdman Mrs.'),
  ('April Muller'),
  ('Ewell Lebsack'),
  ('Shemar Casper'),
  ('Mrs. Ashlee Hoppe'),
  ('Hunter Franecki'),
  ('Janae Feest'),
  ('Miss Camille Krajcik'),
  ('Maymie Davis Ms.'),
  ('Edythe Lubowitz'),
  ('Mavis Gaylord'),
  ('Myriam Kuhic'),
  ('Santino Buckridge'),
  ('Lee Nikolaus'),
  ('Ms. Darien Stiedemann'),
  ('Miss Willy O\'Kon'),
  ('Maye Yundt'),
  ('Kirsten Quitzon'),
  ('May Herzog'),
  ('Russ Thompson'),
  ('Mr. Gustave Kunze'),
  ('Billie McCullough'),
  ('Annie Armstrong'),
  ('Donnie Simonis'),
  ('Retta Huels'),
  ('Daisha Keebler Ms.'),
  ('Levi Kunze'),
  ('Marlen Little Mr.'),
  ('Miss Rae Von'),
  ('Ashlee Kessler'),
  ('Mrs. Gilbert Collier'),
  ('Wilber Fritsch'),
  ('Cayla Dibbert'),
  ('Rosina Labadie'),
  ('Dimitri Sanford'),
  ('Evan Torphy'),
  ('Chet Hintz'),
  ('Alvis Pollich'),
  ('Richard Mann'),
  ('Ms. Milo McDermott'),
  ('Yasmin Herman'),
  ('Sheila Harvey'),
  ('Deron Rodriguez'),
  ('Mr. Rosemarie Raynor'),
  ('Lafayette Ebert'),
  ('Ivory Gislason Ms.'),
  ('Cassie Padberg'),
  ('Karolann Rogahn Mr.'),
  ('Mrs. Kyla Padberg'),
  ('Patience Orn'),
  ('Berniece Kerluke'),
  ('Prudence Sauer'),
  ('Dr. Gina Stiedemann'),
  ('Letitia Hamill'),
  ('Craig Pfannerstill'),
  ('Ethelyn Huel'),
  ('Loyce Terry'),
  ('Natalia O\'Conner'),
  ('Maximo Swaniawski'),
  ('Bryana Douglas'),
  ('Betsy Bednar'),
  ('Drake Harber'),
  ('Marielle Corwin'),
  ('Will Reichert'),
  ('Adolfo Kovacek'),
  ('Reanna Ernser');
